import turtle
turtle.Screen().bgcolor("black")
turtle.Screen().setup(300,400)
polygon=turtle.Turtle()
polygon.color("white")
polygon.forward(100)
polygon.right(120)
polygon.forward(100)
polygon.right(120)
polygon.forward(100)
polygon.penup()
polygon.right(120)
polygon.forward(25)
polygon.pendown()
polygon.left(60)
polygon.forward(40)
polygon.right(120)
polygon.forward(100)
polygon.right(120)
polygon.forward(100)
polygon.right(120)
polygon.forward(60)
turtle.done()


